services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book_management'
      - 'POSTGRES_PASSWORD=3110'
      - 'POSTGRES_USER=app_user'
    ports:
      - '5432:5432'
